# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0006_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='azimut',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='reflectance_angle',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='humidity',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='place_id',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
